config/routes.rb
Watchman::Application.routes.draw do

  resources :users
  resources :projects
  resources :services
  resources :tests do
    delete 'watcher/:watcher_id', :to => 'tests#remove_watcher', :as=>'remove_watcher'
  end
  resources :test_steps
  
  

  root :to => "projects#index"

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :services
end

app/models/service.rb
class Service < ActiveRecord::Base
  belongs_to :project
  has_many :tests

  def status 
    tests.all?{ |t| t.status }
  end
end

app/models/test.rb
require 'celerity'
class Test < ActiveRecord::Base
  belongs_to :service
  has_many :test_steps
  has_many :test_runs
  has_and_belongs_to_many :watchers, :class_name=>'User'

  def execute 
    browser = Celerity::Browser.new( :log_level => :severe, :resynchronize => true, :css => false, :javascript_enabled=>false)
    test_steps.each do |step|
      case step.action
      when 'goto'
        browser.goto('http://dev-franchise.realiefcenters.com')
      when 'Set Value'
        logger.info browser.elements_by_xpath(step.xpath).first
        elem = browser.elements_by_xpath(step.xpath).first
        if (!elem) 
          raise "unable to find element: #{step.xpath}\n#{browser.xml}"
        end 
        elem.value = step.value
      when 'click'
        elem = browser.elements_by_xpath(step.xpath).first
        elem.click
      when 'expect contains'
        #browser.wait
        elem = browser.elements_by_xpath(step.xpath).first
        output = elem.text.include?(step.value)
        if (!output) ## assertion failed
          browser.close()
          return false
        end
      end
    end
    browser.close()
    true
  end

  def run
    run = TestRun.new(:test=>self, :status=>self.execute)
    run.save  
    unless run.status
      watchers.each do |recipient|
        Notifier.alert(recipient, self).deliver # sends the email
      end
    end
  end

  def status
    test_runs.first.status
  end
end

app/models/test_run.rb
class TestRun < ActiveRecord::Base
  belongs_to :test
end

app/models/test_step.rb
class TestStep < ActiveRecord::Base
  belongs_to :test
  default_scope :order => 'id'
  
end

app/models/user.rb
class User < ActiveRecord::Base

  def email_address_with_name
    "#{name} <#{email}>"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.find(:all)
  end

  def new
   @project = Project.new
  end

  def create
    @project = Project.new(params[:project]).save
    redirect_to projects_path
  end

  def show
    @project = Project.find(params[:id])

  end

  def destroy
    @project = Project.find(params[:id])
    @project.delete
    redirect_to projects_path
  end


end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  def new
    @service = Service.new(:project_id=>params[:project_id])
  end

  def create
    @service = Service.new(params[:service])
    @service.save
    logger.info "service " + @service.inspect
    redirect_to service_path(@service)
  end

  def show
    @service = Service.find(params[:id])
  end

  def destroy
    @service = Service.find(params[:id])
    project = @service.project
    @service.delete
    redirect_to project_path(project)
  end

end

app/controllers/test_steps_controller.rb
class TestStepsController < ApplicationController
  def new 
    @test_step = TestStep.new(:test_id => params[:test_id])
  end

  def create
    @test_step = TestStep.new(params[:test_step])
    @test_step.save

    redirect_to test_path(@test_step.test)
  end

  def edit
    @test_step = TestStep.find(params[:id])
    render 'new'
  end

  def update
    @test_step = TestStep.find(params[:id])
    if @test_step.update_attributes(params[:test_step])
      redirect_to test_path(@test_step.test)
    else 
      render 'new'
    end
    
  end

end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  def new
    @test = Test.new(:service_id => params[:service_id])
  end

  def create
    @test = Test.new(params[:test])
    @test.save
    redirect_to test_path(@test)
  end

  def show
    @test = Test.find(params[:id])
  end

  def remove_watcher
    @test = Test.find(params[:test_id])
    @watcher = User.find(params[:watcher_id])
    @test.watchers.delete(@watcher)
    redirect_to test_path(@test)
  end

  def update
    @test = Test.find(params[:id])

    if (params[:test][:new_watcher])
      @test.watchers << User.find(params[:test][:new_watcher])
    end
    
    redirect_to test_path(@test)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.find(:all)
  end
  
  def new
    @user = User.new()
  end

  def create
    @user = User.new(params[:user])
    @user.save
    redirect_to users_path
  end

  def show
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    @user.delete
    redirect_to users_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/test_steps_helper.rb
module TestStepsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Watchman</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/projects.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Watchman Projects</title>
  <%= stylesheet_link_tag params[:controller] %>
  <%= stylesheet_link_tag 'application' %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
  <nav><%=link_to "Home", root_path%>
  <% if @project %>
    &raquo; <%=@project.name%>
  <% end %>
  </nav>

<%= yield %>

</body>
</html>

app/views/layouts/services.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Watchman Tests</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

  <nav><%=link_to "Home", root_path%> &raquo; <%=link_to "Project: #{@service.project.name}", project_path(@service.project)%> &raquo; <%=@service.name %></nav>

<%= yield %>

</body>
</html>

app/views/layouts/tests.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Watchman Tests</title>
  <%= stylesheet_link_tag params[:controller] %>
  <%= stylesheet_link_tag 'application' %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

  <nav><%=link_to "Home", root_path%> &raquo; <%=link_to "Project: #{@test.service.project.name}", project_path(@test.service.project)%> &raquo; 
    <%=link_to "Service: #{@test.service.name}", service_path(@test.service)%> &raquo; <%= @test.name %></nav>

<%= yield %>

</body>
</html>

app/views/notifier/alert.text.plain.erb
There was a problem running the test.

<%= @test.name %>

app/views/projects/index.html.erb
<h1>Projects</h1>
<ul>
<% @projects.each do |project| %>
  <li><%= link_to project.name, project_path(project) %>
      <%= link_to 'Delete', project_path(project),
            :confirm => 'Are you sure?', :method => :delete %>
  </li>

<% end %>
</ul>

<%=link_to 'Add new', new_project_path %>

app/views/projects/new.html.erb
<h1>Create a new project</h1>
<% form_for @project do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/projects/show.html.erb
<h1><%= @project.name %> </h1>

<h2>Services</h2>
<table>
<% @project.services.each do |service| %>
  <tr>
    <td><%=link_to service.name, service_path(service)%></td>
    <td class="<%= service.status ? 'pass' : 'fail'%>" ><%=service.status ? 'PASS' : 'FAIL' %></td>
    <td><%= link_to 'Delete', service_path(service),
            :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>
<%=link_to 'Add new service', new_service_path(:project_id=>@project) %>

app/views/services/new.html.erb
<h1>Create a new service</h1>
<% form_for @service do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.hidden_field :project_id %>
  <%= f.submit %>
<% end %>

app/views/services/show.html.erb
<h1><%= @service.name %> </h1>

<h2>Tests</h2>
<ul>
<% @service.tests.each do |test| %>
  <li><%= link_to test.name, test_path(test)%></li>
<% end %>
</ul>
<%=link_to 'Add new test', new_test_path(:service_id=>@service.id) %>

app/views/test_steps/new.html.erb
<h1>Create a new step</h1>
<% form_for @test_step do |f| %>
  <%= f.label :action %>
  <%= f.text_field :action %><br>
  <%= f.label :xpath %>
  <%= f.text_field :xpath %><br>
  <%= f.label :value %>
  <%= f.text_field :value %><br>
  <%= f.hidden_field :test_id %>
  <%= f.submit %>
<% end %>

app/views/users/index.html.erb
<h1>Users</h1>
<ul>
<% @users.each do |user| %>
  <li><%= link_to user.name, user_path(user) %>
      <%= link_to 'Delete', user_path(user),
            :confirm => 'Are you sure?', :method => :delete %>
  </li>

<% end %>
</ul>

<%=link_to 'Add new', new_user_path %>

app/views/users/new.html.erb
<h1>Create a new user</h1>
<% form_for @user do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br/>
  <%= f.label :email %>
  <%= f.text_field :email %><br/>
  <%= f.submit %>
<% end %>